stages:
  - deploy

variables:
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_BUILDKIT: 1
    APP_NAME: my-first-app

deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - helm ls -A
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always