stages:
  - deploy

variables:
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_BUILDKIT: 1
    APP_NAME: my-first-app

deploy:
  stage: deploy
  image: 
    name: alpine/helm:latest
    entrypoint: [""]
    pull_policy: always
  script:
    - helm ls -A
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always