stages:
  - deploy2

variables:
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_BUILDKIT: 1
    APP_NAME: my-first-app

#deploy:
#  image: 
#    name: alpine/helm:latest
#    entrypoint: [""]
#    pull_policy: always
#  script:
#    - helm ls -A
#  rules:
#    - if: $CI_COMMIT_BRANCH == 'main'
#      when: always


deploy2:
  stage: deploy2
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context path/to/agent/repository:agent-name
    - kubectl get pods
