stages:
  - deploy

variables:
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_BUILDKIT: 1
    APP_NAME: my-first-app

deploy:
  stage: deploy
  image: 
    name: dtzar/helm-kubectl:3.11.3
    entrypoint: [""]
    pull_policy: always
  script:
    - kubectl config use-context cloudcauldron/mastodon-chart:google-cloud-mastodon

    - helm ls -A
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always

