name: 'Sync to Gitlab'

on:
  push:
    branches: ['main']

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync Repository from GitHub to GitLab
    steps:
      - uses: actions/checkout@v2
      - uses: adambirds/sync-github-to-gitlab-action@v1.1.0
        with:
          destination_repository: git@gitlab.cloudcauldron.io:cloudcauldron/mastodon-chart.git
          destination_branch_name: main
          destination_ssh_key: ${{ secrets.GITLAB_SSH_KEY }}

